// Frame HTML: trang chat mini render trong <iframe>, tự chứa (style + script nội tuyến).
import { escapeWidgetHtml, WIDGET_DEFAULT_COLOR } from "./embed.js";

// Nhúng giá trị động vào <script> an toàn: JSON.stringify KHÔNG escape "<",
// attacker có thể gửi chuỗi dạng đóng-thẻ-script để thoát thẻ script. Đổi mọi "<"
// thành chuỗi escape unicode 003c (tương đương trong chuỗi JS, vô hại với HTML parser).
function jsEmbed(v: unknown): string {
  return JSON.stringify(v).replace(/</g, "\\u003c");
}

export interface BuildFrameHtmlOpts {
  botId: string;
  widgetKey: string;
  visitorId: string;
  title: string;
  color: string;
  greeting: string;
}

export function buildFrameHtml(opts: BuildFrameHtmlOpts): string {
  const { botId, widgetKey, visitorId, title, color, greeting } = opts;
  const safeTitle = escapeWidgetHtml(title);
  const safeColor = /^#[0-9a-fA-F]{6}$/.test(color) ? color : WIDGET_DEFAULT_COLOR;

  // botId xuất hiện trong 1 dòng comment của script — dù là comment JS, "<" vẫn được
  // HTML parser đọc, nên cũng phải chặn breakout như mọi giá trị nhúng khác.
  const botIdForComment = botId.replace(/</g, "\\u003c");

  // greeting nhúng THÔ qua jsEmbed (đường JS → textContent, không phải HTML):
  // jsEmbed đã chặn breakout, còn textContent hiển thị đúng ký tự gốc (& < > " ').
  const clientConfig = jsEmbed({
    botId,
    key: widgetKey,
    visitor: visitorId,
    greeting,
  });

  return [
    "<!doctype html>",
    '<html lang="vi">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>${safeTitle}</title>`,
    "<style>",
    "  html, body { margin:0; padding:0; height:100%; }",
    "  body {",
    "    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;",
    "    display: flex; flex-direction: column; height: 100%; background: #fff;",
    "  }",
    "  #hdr {",
    `    background: ${safeColor}; color: #fff; padding: 12px 16px;`,
    "    font-weight: 600; font-size: 15px; flex: none;",
    "  }",
    "  #msgs {",
    "    flex: 1 1 auto; overflow-y: auto; padding: 12px; background: #fff;",
    "  }",
    "  .msg { max-width: 80%; margin-bottom: 8px; padding: 8px 12px; border-radius: 12px; font-size: 14px; line-height: 1.4; white-space: pre-wrap; word-break: break-word; }",
    "  .msg.user {",
    `    margin-left: auto; background: ${safeColor}; color: #fff; border-bottom-right-radius: 4px;`,
    "  }",
    "  .msg.bot {",
    "    margin-right: auto; background: #f1f5f9; color: #0f172a; border-bottom-left-radius: 4px;",
    "  }",
    "  .msg.system {",
    "    margin: 0 auto 8px; text-align: center; background: none; color: #94a3b8; font-size: 12px; max-width: 100%;",
    "  }",
    "  #frm {",
    "    display: flex; gap: 8px; padding: 10px; border-top: 1px solid #e2e8f0; flex: none;",
    "  }",
    "  #inp {",
    "    flex: 1 1 auto; border: 1px solid #cbd5e1; border-radius: 20px; padding: 8px 14px;",
    "    font-size: 14px; outline: none; min-width: 0;",
    "  }",
    "  #snd {",
    `    background: ${safeColor}; color: #fff; border: 0; border-radius: 20px;`,
    "    padding: 8px 16px; font-size: 14px; cursor: pointer; flex: none;",
    "  }",
    "</style>",
    "</head>",
    "<body>",
    `<div id="hdr">${safeTitle}</div>`,
    '<div id="msgs"></div>',
    '<form id="frm">',
    '<input id="inp" placeholder="Nhập tin nhắn..." autocomplete="off">',
    '<button id="snd" type="submit">Gửi</button>',
    "</form>",
    "<script>",
    "(function () {",
    '  "use strict";',
    "  var CFG = " + clientConfig + ";",
    "  var KEY = CFG.key;",
    "  var VISITOR = CFG.visitor;",
    "  var GREETING = CFG.greeting;",
    "",
    "  // API tinh dong tu URL frame hien tai (chay dung ca qua proxy /balabot lan goi thang Railway).",
    "  // Voi bot nay, endpoint thuc te la: /api/widget/" + botIdForComment + "/chat , /api/widget/" + botIdForComment + "/messages",
    "  var API = location.pathname.replace(/\\/frame.*$/, \"\");",
    "",
    "  var msgsEl = document.getElementById(\"msgs\");",
    "  var frmEl = document.getElementById(\"frm\");",
    "  var inpEl = document.getElementById(\"inp\");",
    "",
    "  var lastTs = null;",
    "  var typingEl = null;",
    "",
    "  function scrollDown() {",
    "    msgsEl.scrollTop = msgsEl.scrollHeight;",
    "  }",
    "",
    "  function addMsg(sender, text) {",
    "    var el = document.createElement(\"div\");",
    "    el.className = \"msg \" + (sender === \"user\" ? \"user\" : sender === \"system\" ? \"system\" : \"bot\");",
    "    el.textContent = text;",
    "    msgsEl.appendChild(el);",
    "    scrollDown();",
    "    return el;",
    "  }",
    "",
    "  function showTyping() {",
    "    hideTyping();",
    "    typingEl = addMsg(\"bot\", \"...\");",
    "  }",
    "",
    "  function hideTyping() {",
    "    if (typingEl && typingEl.parentNode) typingEl.parentNode.removeChild(typingEl);",
    "    typingEl = null;",
    "  }",
    "",
    "  function fetchJson(url, options, timeoutMs) {",
    "    var controller = (typeof AbortController !== \"undefined\") ? new AbortController() : null;",
    "    var opts = options || {};",
    "    if (controller) opts.signal = controller.signal;",
    "    var timer = controller ? setTimeout(function () { controller.abort(); }, timeoutMs || 30000) : null;",
    "    return fetch(url, opts).then(function (res) {",
    "      if (timer) clearTimeout(timer);",
    "      if (!res.ok) throw new Error(\"http \" + res.status);",
    "      return res.json();",
    "    }).catch(function (err) {",
    "      if (timer) clearTimeout(timer);",
    "      throw err;",
    "    });",
    "  }",
    "",
    "  function renderInitial(messages) {",
    "    if (!messages || messages.length === 0) {",
    "      addMsg(\"bot\", GREETING);",
    "      return;",
    "    }",
    "    for (var i = 0; i < messages.length; i++) {",
    "      var m = messages[i];",
    "      addMsg(m.sender, m.text);",
    "      lastTs = m.timestamp;",
    "    }",
    "  }",
    "",
    "  function renderAppended(messages) {",
    "    for (var i = 0; i < messages.length; i++) {",
    "      var m = messages[i];",
    "      addMsg(m.sender, m.text);",
    "      lastTs = m.timestamp;",
    "    }",
    "  }",
    "",
    "  function poll() {",
    "    var url = API + \"/messages?key=\" + encodeURIComponent(KEY) +",
    "      \"&visitor=\" + encodeURIComponent(VISITOR) +",
    "      (lastTs ? \"&after=\" + encodeURIComponent(lastTs) : \"\");",
    "    fetchJson(url, {}, 30000).then(function (data) {",
    "      var messages = (data && data.messages) || [];",
    "      if (messages.length) renderAppended(messages);",
    "    }).catch(function () {});",
    "  }",
    "",
    "  function init() {",
    "    var url = API + \"/messages?key=\" + encodeURIComponent(KEY) +",
    "      \"&visitor=\" + encodeURIComponent(VISITOR);",
    "    fetchJson(url, {}, 30000).then(function (data) {",
    "      var messages = (data && data.messages) || [];",
    "      renderInitial(messages);",
    "    }).catch(function () {",
    "      addMsg(\"bot\", GREETING);",
    "    });",
    "    setInterval(poll, 5000);",
    "  }",
    "",
    "  frmEl.addEventListener(\"submit\", function (ev) {",
    "    ev.preventDefault();",
    "    var text = inpEl.value.trim();",
    "    if (!text) return;",
    "    inpEl.value = \"\";",
    "    addMsg(\"user\", text);",
    "    showTyping();",
    "    var url = API + \"/chat\";",
    "    fetchJson(url, {",
    "      method: \"POST\",",
    "      headers: { \"Content-Type\": \"application/json\" },",
    "      body: JSON.stringify({ key: KEY, visitor: VISITOR, text: text }),",
    "    }, 30000).then(function (data) {",
    "      hideTyping();",
    "      var reply = data && data.reply;",
    "      var humanTakeover = data && data.humanTakeover;",
    "      // Backend trả ts = timestamp tin bot: cập nhật lastTs để poll không append lại",
    "      // chính tin này (chống nhân đôi bubble). Không có ts thì giữ nguyên lastTs.",
    "      if (data && data.ts) lastTs = data.ts;",
    "      if (reply) {",
    "        addMsg(\"bot\", reply);",
    "      } else if (humanTakeover) {",
    "        addMsg(\"system\", \"Nhân viên đang hỗ trợ anh/chị trực tiếp ạ.\");",
    "      }",
    "    }).catch(function () {",
    "      hideTyping();",
    "      addMsg(\"system\", \"Mạng chậm, anh/chị thử lại giúp em ạ.\");",
    "    });",
    "  });",
    "",
    "  init();",
    "})();",
    "</script>",
    "</body>",
    "</html>",
  ].join("\n");
}
