// Loader JS: chạy trên website của shop (script tag async), vẽ bong bóng chat.
// LƯU Ý: chuỗi trả về KHÔNG được chứa backtick — viết bằng nối chuỗi "\n" thường,
// vì nội dung này sẽ được phục vụ y nguyên như một file .js tĩnh cho trình duyệt.

export function buildLoaderJs(): string {
  const lines: string[] = [
    '(function () {',
    '  "use strict";',
    '  if (window.__balabotWidget) return;',
    '  window.__balabotWidget = true;',
    '',
    '  var s = document.currentScript;',
    '  if (!s) return;',
    '  var botId = s.getAttribute("data-bot");',
    '  var key = s.getAttribute("data-key");',
    '  if (!botId || !key) return;',
    '',
    '  var base = s.src.replace(/\\/api\\/widget\\/loader\\.js.*$/, "");',
    '',
    '  function makeVisitorId() {',
    '    return "wv-" + (',
    '      Math.random().toString(36).slice(2) +',
    '      Math.random().toString(36).slice(2)',
    '    ).slice(0, 22);',
    '  }',
    '',
    '  var visitorId;',
    '  try {',
    '    var storeKey = "balabot-visitor-" + botId;',
    '    visitorId = localStorage.getItem(storeKey);',
    '    if (!visitorId) {',
    '      visitorId = makeVisitorId();',
    '      localStorage.setItem(storeKey, visitorId);',
    '    }',
    '  } catch (e) {',
    '    visitorId = makeVisitorId();',
    '  }',
    '',
    '  var open = false;',
    '  var btn = null;',
    '  var iframe = null;',
    '',
    '  var ICON_CHAT =',
    '    \'<svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>\';',
    '  var ICON_CLOSE =',
    '    \'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>\';',
    '',
    '  function closeFrame() {',
    '    if (iframe && iframe.parentNode) iframe.parentNode.removeChild(iframe);',
    '    iframe = null;',
    '    open = false;',
    '    if (btn) btn.innerHTML = ICON_CHAT;',
    '  }',
    '',
    '  function openFrame() {',
    '    iframe = document.createElement("iframe");',
    '    iframe.setAttribute(',
    '      "style",',
    '      "position:fixed;right:20px;bottom:88px;width:380px;height:560px;" +',
    '      "max-width:calc(100vw - 32px);max-height:calc(100vh - 110px);" +',
    '      "border:0;border-radius:16px;box-shadow:0 12px 40px rgba(0,0,0,.22);" +',
    '      "z-index:2147483000;background:#fff;"',
    '    );',
    '    iframe.src =',
    '      base + "/api/widget/" + botId + "/frame?key=" + encodeURIComponent(key) +',
    '      "&visitor=" + encodeURIComponent(visitorId);',
    '    document.body.appendChild(iframe);',
    '    open = true;',
    '    if (btn) btn.innerHTML = ICON_CLOSE;',
    '  }',
    '',
    '  function toggle() {',
    '    if (open) {',
    '      closeFrame();',
    '    } else {',
    '      openFrame();',
    '    }',
    '  }',
    '',
    '  function renderButton(color) {',
    '    btn = document.createElement("button");',
    '    btn.type = "button";',
    '    btn.setAttribute("aria-label", "Chat");',
    '    btn.innerHTML = ICON_CHAT;',
    '    btn.setAttribute(',
    '      "style",',
    '      "position:fixed;right:20px;bottom:20px;width:56px;height:56px;" +',
    '      "border-radius:50%;z-index:2147483000;border:0;cursor:pointer;" +',
    '      "display:flex;align-items:center;justify-content:center;" +',
    '      "box-shadow:0 6px 20px rgba(0,0,0,.25);" +',
    '      "background:" + color + ";" +',
    '      "transition:transform .15s ease;"',
    '    );',
    '    btn.onmouseenter = function () {',
    '      btn.style.transform = "scale(1.08)";',
    '    };',
    '    btn.onmouseleave = function () {',
    '      btn.style.transform = "scale(1)";',
    '    };',
    '    btn.onclick = toggle;',
    '    document.body.appendChild(btn);',
    '  }',
    '',
    '  fetch(base + "/api/widget/" + botId + "/config?key=" + encodeURIComponent(key))',
    '    .then(function (res) {',
    '      if (!res.ok) return null;',
    '      return res.json();',
    '    })',
    '    .then(function (cfg) {',
    '      if (!cfg) return;',
    '      var color = cfg.color || "#059669";',
    '      renderButton(color);',
    '    })',
    '    .catch(function () {});',
    '})();',
  ];
  return lines.join("\n");
}
